FROM golang:1.22-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN go build -o worker ./cmd/worker

FROM alpine:3.19
COPY --from=builder /app/worker /worker
ENTRYPOINT ["/worker"]
